; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri May 21 2021 03:05:15 GMT-0700 (Pacific Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


