; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun May 23 2021 16:36:21 GMT-0700 (Pacific Daylight Time)
G91               ; relative positioning
G90 ; absolute position
G1 X95 Y100 F1000 ; move probe to center of bed
G30

; Uncomment the following lines to lift Z after probing
G91                  ; relative positioning
G1 H1 Z210 F1000      ; lift Z relative to current position
G90                  ; absolute positioning

