; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri May 21 2021 03:05:15 GMT-0700 (Pacific Daylight Time)
M280 P0 S90 ; retract BLTouch

