; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Fri May 21 2021 03:05:17 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0

